### ISSUE TITLE
SSLError when attempting to connect

### ISSUE THREAD

**Issue by bubthegreat** [tubaman/bankscrape#3]
Looks like maybe this hasn't been used in a while - but it's throwing an SSL error when attempting to connect to the URL:

```
(wfscraper) micheal.taylor@bubdev ~/bankscrape/scripts (master) $ python bankscrape wellsfargo -f config
Traceback (most recent call last):
  File "bankscrape", line 32, in <module>
    csv = bank.scrape(config_items)
  File "/home/micheal.taylor/.virtualenvs/wfscraper/local/lib/python2.7/site-packages/bankscrape/banks/wellsfargo.py", line 94, in scrape
    main_page_html = login(username, password)
  File "/home/micheal.taylor/.virtualenvs/wfscraper/local/lib/python2.7/site-packages/bankscrape/banks/wellsfargo.py", line 35, in login
    SCRAPER.get('https://www.wellsfargo.com/')
  File "/home/micheal.taylor/.virtualenvs/wfscraper/local/lib/python2.7/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/home/micheal.taylor/.virtualenvs/wfscraper/local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/micheal.taylor/.virtualenvs/wfscraper/local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/micheal.taylor/.virtualenvs/wfscraper/local/lib/python2.7/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.wellsfargo.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, u'[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)'),))

```

**Comment by Aerex** [comment]
@bubthegreat So I know why this is happening. The api for Wells Fargo has changed. If you try to go to https://wellsfargo.com/signon your browser will
tell you that the page does not exist. The new page is https://connect.secure.wellsfargo/auth/login/do. Unfortuantely, the POST requires a secure token that I am sure is generated from the server so mocking this using simple CRUD operations is not going to work. I am going to see if simulating button presses by using something like phantomJS will circumvent this problem. Once you can login getting the CSV should be fairly easy.

**Comment by leonmcd** [comment]
Has this issue been resolved? Will this code work now?

**Comment by justinTM** [comment]
possibly changed to https://connect.secure.wellsfargo.com/auth/login/present
